spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: jdbc:${DB_PREFIX:mysql}://${DB_ADDR:localhost}:${DB_PORT:3306}/${DB_NAME:test}
    username: spring-user
    password: secret
    continue-on-error: true